Proceso CICLO_MIENTRAS_PROBLEMA1
	
	//EJEMPLO 1:
	//IMPLEMENTAR UN ALGORITMO EL CUAL PERMITA
	//MOSTRAR SU NOMBRE 10 VECES.
	CONTADOR<-0
	Mientras CONTADOR<10 Hacer
		CONTADOR<-CONTADOR+1
		Escribir CONTADOR, "PIKACHU"
	Fin Mientras
	
FinProceso
